/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#f8f9ff',
          dim: '#d4dae7',
          bright: '#f8f9ff',
          'container-lowest': '#ffffff',
          'container-low': '#eff4ff',
          container: '#e7eefb',
          'container-high': '#e2e8f6',
          'container-highest': '#dce3f0',
          variant: '#dce3f0',
        },
        background: '#f8f9ff',
        primary: {
          DEFAULT: '#002f35',
          container: '#07474e',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#80b4bc',
        'surface-tint': '#30666d',
        secondary: {
          DEFAULT: '#ae2f34',
          container: '#ff6b6b',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6d0010',
        'on-surface': '#151c25',
        'on-surface-variant': '#40484a',
        outline: '#70797a',
        'outline-variant': '#bfc8c9',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'primary-fixed': '#b6ecf4',
        'primary-fixed-dim': '#9acfd8',
        'on-primary-fixed': '#001f23',
        'on-primary-fixed-variant': '#134e55',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#ffb3b0',
        'on-secondary-fixed': '#410006',
        'on-secondary-fixed-variant': '#8c1520',
        'tertiary-fixed': '#e8e2d4',
        'tertiary-fixed-dim': '#cbc6b9',
        'on-tertiary-fixed': '#1d1c13',
        'on-tertiary-fixed-variant': '#49473d',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      fontSize: {
        'headline-xl': ['48px', '1.2'],
        'headline-lg': ['32px', '1.25'],
        'headline-lg-mobile': ['28px', '1.3'],
        'headline-md': ['24px', '1.4'],
        'body-lg': ['18px', '1.6'],
        'body-md': ['16px', '1.6'],
        'label-md': ['14px', '1.4'],
        'label-sm': ['12px', '1.4'],
      },
      boxShadow: {
        'elevation-soft': '0 2px 8px rgba(0, 47, 53, 0.06)',
        'elevation-hover': '0 6px 18px rgba(0, 47, 53, 0.10)',
      },
    },
  },
  plugins: [],
}
